version: "3"
services:
  firebase:
    container_name: ryoheymeeting_firebase_mock
    hostname: ryoheymeeting_firebase
    env_file:
      - .env.firebase
    build:
      context: .
      dockerfile: ".docker/Dockerfile.firebase"
    volumes:
      - firebase:/firebase
    tty: true
    working_dir: /firebase
    command: yarn start
    ports:
      - 4000:4000 # Emulator Suite UI
      - 9099:9099 # Authentication
      #- 5000:5000 # Firebase Hosting
      #- 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 9199:9199 # Storage
      #- 8085:8085 # Cloud Pub/Sub
      - 4400:4400 # Emuylator Hub
      - 4500:4500 # Other reserved ports
  frontend:
    container_name: ryoheymeeting_frontend
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: "./.docker/Dockerfile.frontend"
    image: ryoheymeeting_frontend
    volumes:
      - .:/frontend
      - node_modules:/frontend/node_modules
    tty: true
    working_dir: /frontend
    command: yarn start
    ports:
      - 3000:3000
    links:
      - firebase
  storybook:
    container_name: ryoheymeeting_storybook
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    image: ryoheymeeting_frontend
    volumes:
      - .:/frontend
      - node_modules:/frontend/node_modules
    tty: true
    working_dir: /frontend
    command: yarn storybook
    ports:
      - 6006:6006
    links:
      - frontend
volumes:
  firebase:
  node_modules:
