version: "3"
services:
  ryoheynode:
    image: node:16.14.2
    volumes:
      - .:/project
    tty: true
    working_dir: /project
    command: bash
    ports:
      - "3000:3000"
      - "6006:6006"
