FROM node:16.14.2

RUN apt-get update -y

RUN apt-get install -y openjdk-11-jre-headless

RUN rm -rf /firebase
RUN git clone https://github.com/RyoheyMeeting/ryoheymeeting_firebase.git /firebase

ENV APP_ROOT /firebase
WORKDIR ${APP_ROOT}

ADD ./.env.firebase ${APP_ROOT}/.env
RUN yarn install

CMD ["yarn", "start"]
